### ISSUE TITLE
Outdated dependencies. Maybe add the lock file?

### ISSUE THREAD

**Issue by webmuch** [simpletut/Universal-React-Apollo-Registration#13]
Hey do you intend to move it to 16.8 anytime soon? I am trying but I'm unable to upgrade depreciated libraries with new ones, without the project failing. I'll try to setup a new project with the ideas from this repo. Perhaps add the lock file so "npm i" just works.

**Comment by simpletut** [comment]
@webmuch 

Yes this is something I am currently working on. 

I have already upgraded the Redux version of this project. See here:

https://github.com/simpletut/Universal-React-Redux-Registration

**Comment by simpletut** [comment]
Just merged a major PR that updates the project to use the latest version of React `v16.8.6`

PR: https://github.com/simpletut/Universal-React-Apollo-Registration/pull/14
