### ISSUE TITLE
variable.env

### ISSUE THREAD

**Issue by cichy** [simpletut/Universal-React-Apollo-Registration#15]
There is no variable.env file. I followed the instructions and I get an Error: Environment variable 'dbString' is not defined.

**Comment by simpletut** [comment]
We no longer use the `variable.env` to define environment variables. (Documentation needs to be updated)

The application is programmed to exit if the important env vars are not defined.

Before you try and run the application, set the env var using the following:

(Mac) 
`export dbString =<Your-dbString >`

**Comment by cichy** [comment]
still getting the same error

**Comment by simpletut** [comment]
I am closing this issue as it is not an error in the code.

Make sure you do not leave any gaps between the var name and value i.e `<name>=<value>`

Example: 

`export dbString=<Your-dbString >` 

If you still get the same message, log your current env var to the console and check it has been defined.

**Comment by W00DH0USE** [comment]
Hey did you manage to fix this issue as I'm getting the same error?
